<?php

namespace Processwire;

class ContactPageManager extends WireData implements Module,ConfigurableModule{
	
	public function __construct(){
		foreach(self::getDefaultData() as $key=>$value){
			$this->{
				$key
			}
			=$value;
		}
	}
	public static function getModuleInfo() {
		return array(
		            'title' => 'Contact Page Manager',
		            'version' => "1.0.0",
		            'author' => 'dojoVader/Sephiroth',
		            'summary' => 'This module simply logs all contact messages to the Database for you to see, this is meant as a tutorial',
		            'href' => 'https://github.com/dojoVader/ContactPageManager',
		            'autoload' => false, // 		set to true if module should auto-load at boot
		                'requires' => array(
		                    'PHP>=5.4.1', 
		                    'ProcessWire>=2.4.1'
		                    )
		
		);
	}
	
	static function getDefaultData(){
		return [
		            "contact_email"=>""   
		        ];
	}
	
	
	/**
	* Return an InputfieldsWrapper of Inputfields used to configure the class
	     *
	     * @param array $data Array of config values indexed by field name
	     * @return InputfieldsWrapper
	     *
	     */
	    public static function getModuleConfigInputfields(array $data) {
		
		$data = array_merge(self::getDefaultData(), $data);
		
		$wrapper = new InputFieldWrapper();
		
		$f = wire('modules')->get("InputfieldEmail");
		$f->attr('id+name', 'contact_email');
		$f->label = __("Enter a valid email to be used to notify user");
		$f->description = __("Email Address");
		$f->value = $data['contact_email'];
		$wrapper->add($f);
		
		return $wrapper;
		
	}
	
}
